name: Required quality proof

on:
  pull_request:

permissions:
  contents: read

jobs:
  required-quality:
    uses: RocketsAreNostalgic/.github/.github/workflows/required-quality-node.yml@18a63f8816026c0c2e63b9434d238a4093702e68
